export type Category =
  | 'abatelenguas'
  | 'aplicadores'
  | 'laboratorio'
  | 'guantes'
  | 'cubrebocas'
  | 'ropa'
  | 'residuos'
  | 'ginecologia'

export interface Product {
  id: number
  slug: string
  name: string
  description: string
  unit: string
  price: number
  category: Category
  image: string
  keywords: string[]
}

export const categories: { id: Category | 'todos'; label: string }[] = [
  { id: 'todos', label: 'Todos' },
  { id: 'abatelenguas', label: 'Abatelenguas' },
  { id: 'aplicadores', label: 'Aplicadores' },
  { id: 'laboratorio', label: 'Laboratorio' },
  { id: 'guantes', label: 'Guantes' },
  { id: 'cubrebocas', label: 'Cubrebocas' },
  { id: 'ropa', label: 'Ropa desechable' },
  { id: 'residuos', label: 'Residuos RPBI' },
  { id: 'ginecologia', label: 'Ginecología' },
]

export const products: Product[] = [
  {
    id: 1,
    slug: 'abatelenguas-granel',
    name: 'Abatelenguas a granel',
    description: 'Abatelenguas de madera de primera calidad, sin astillas, ideales para consultorios médicos y clínicas.',
    unit: 'Bolsa 500 pzas',
    price: 128,
    category: 'abatelenguas',
    image: '/images/Abatelenguas-a-granel.jpg',
    keywords: ['abatelenguas', 'baja lenguas', 'madera', 'consultorio'],
  },
  {
    id: 2,
    slug: 'abatelenguas-esteril',
    name: 'Abatelenguas estéril',
    description: 'Abatelenguas de madera individualmente esterilizados y empacados. Ideales para procedimientos que requieren asepsia.',
    unit: 'Caja 100 pzas',
    price: 218,
    category: 'abatelenguas',
    image: '/images/Abatelenguas-estéril.jpg',
    keywords: ['abatelenguas estéril', 'baja lenguas estéril'],
  },
  {
    id: 3,
    slug: 'abatelenguas-20-25',
    name: 'Abatelenguas paquete 20-25',
    description: 'Paquetes individuales de 20 a 25 abatelenguas de madera. Presentación práctica para uso diario.',
    unit: 'Paquete',
    price: 18,
    category: 'abatelenguas',
    image: '/images/Abatelenguas-20---25.jpg',
    keywords: ['abatelenguas paquete pequeño'],
  },
  {
    id: 4,
    slug: 'aplicador-madera-sin-algodon',
    name: 'Aplicador de madera sin algodón',
    description: 'Aplicadores de madera sin cabeza de algodón. Versátiles para diferentes usos clínicos y de laboratorio.',
    unit: 'Bolsa 100 pzas',
    price: 82,
    category: 'aplicadores',
    image: '/images/Aplicador-de-madera-sin-algodón.jpg',
    keywords: ['aplicador madera', 'hisopo madera'],
  },
  {
    id: 5,
    slug: 'aplicador-madera-con-algodon',
    name: 'Aplicador de madera con algodón',
    description: 'Aplicadores de madera con cabeza de algodón absorbente. Ideales para toma de muestras y aplicación de antisépticos.',
    unit: 'Bolsa 100 pzas',
    price: 102,
    category: 'aplicadores',
    image: '/images/Aplicador-de-madera-con-100.jpg',
    keywords: ['aplicador algodón', 'hisopo', 'toma de muestra'],
  },
  {
    id: 6,
    slug: 'aplicador-plastico-esteril',
    name: 'Aplicador de plástico estéril',
    description: 'Aplicadores de plástico esterilizados individualmente. Libres de látex, empaque hermético para garantizar asepsia.',
    unit: 'Caja 100 pzas',
    price: 165,
    category: 'aplicadores',
    image: '/images/Aplicador-de-plástico-estéril-1-100.jpg',
    keywords: ['aplicador plástico', 'hisopo estéril', 'libre de látex'],
  },
  {
    id: 7,
    slug: 'aplicador-madera-esteril',
    name: 'Aplicador de madera estéril',
    description: 'Aplicadores de madera con algodón, esterilizados. Empaque individual sellado, ideales para procedimientos médicos.',
    unit: 'Caja 100 pzas',
    price: 180,
    category: 'aplicadores',
    image: '/images/Aplicador-de-madera-estéril-1-100.jpg',
    keywords: ['aplicador madera estéril', 'hisopo estéril madera'],
  },
  {
    id: 8,
    slug: 'asa-nicromo-calibrada',
    name: 'Asa de nicromo calibrada 1µL',
    description: 'Asa bacteriológica de nicromo calibrada de 1 microlitro. Fabricada con alambre de alta resistencia para uso en laboratorio microbiológico.',
    unit: 'Caja 100 pzas',
    price: 270,
    category: 'laboratorio',
    image: '/images/Asa-de-nicromo-calibrada-1-100.jpg',
    keywords: ['asa nicromo', 'asa bacteriológica', 'microbiología', 'laboratorio'],
  },
  {
    id: 9,
    slug: 'asa-nicromo-sin-calibrar',
    name: 'Asa de nicromo sin calibrar',
    description: 'Asa de nicromo estándar sin calibrar para siembra y subcultivos microbiológicos.',
    unit: 'Caja 100 pzas',
    price: 210,
    category: 'laboratorio',
    image: '/images/Asa-de-nicromo-sin-calibrar.jpg',
    keywords: ['asa nicromo', 'asa sin calibrar', 'microbiología'],
  },
  {
    id: 10,
    slug: 'cepillo-citologico',
    name: 'Cepillo citológico estéril',
    description: 'Cepillo citológico para obtención de muestras endocervicales. Empaque individual estéril, excelente captación celular.',
    unit: 'Caja 100 pzas',
    price: 480,
    category: 'ginecologia',
    image: '/images/Cepillo-citológico.jpg',
    keywords: ['cepillo citológico', 'muestra endocervical', 'papanicolaou', 'ginecología'],
  },
  {
    id: 11,
    slug: 'espatula-ayre',
    name: 'Espátula de Ayre estéril',
    description: 'Espátula de Ayre de madera estéril para toma de muestra cervical. Diseño ergonómico, empaque individual.',
    unit: 'Caja 100 pzas',
    price: 270,
    category: 'ginecologia',
    image: '/images/Espátula-de-ayre-estéril.jpg',
    keywords: ['espátula ayre', 'colposcopia', 'papanicolaou', 'muestra cervical'],
  },
  {
    id: 12,
    slug: 'espejo-vaginal',
    name: 'Espejo vaginal desechable',
    description: 'Espejo vaginal de poliestireno de alta transparencia. Disponible en tallas S, M y L. Un solo uso para máxima higiene.',
    unit: 'Caja 25 pzas',
    price: 435,
    category: 'ginecologia',
    image: '/images/Espejo-vaginal.jpg',
    keywords: ['espejo vaginal', 'espéculo', 'ginecología', 'exploración'],
  },
  {
    id: 13,
    slug: 'kit-ginecologico',
    name: 'Kit ginecológico completo',
    description: 'Kit completo con espejo vaginal, espátula de Ayre, cepillo citológico y portaobjetos. Ideal para consultorios de ginecología.',
    unit: 'Caja 25 kits',
    price: 1020,
    category: 'ginecologia',
    image: '/images/kit.jpg',
    keywords: ['kit ginecológico', 'papanicolaou', 'colposcopia', 'ginecología completo'],
  },
  {
    id: 14,
    slug: 'guante-latex-exploracion',
    name: 'Guante de látex para exploración',
    description: 'Guantes de látex natural sin polvo para exploración médica. Alta sensibilidad táctil. Tallas S, M y L.',
    unit: 'Caja 100 pzas',
    price: 218,
    category: 'guantes',
    image: '/images/Guante-de-latex.jpg',
    keywords: ['guante látex', 'guante médico', 'exploración', 'sin polvo'],
  },
  {
    id: 15,
    slug: 'guante-polietileno',
    name: 'Guante de polietileno',
    description: 'Guantes de polietileno transparente de bajo costo. Libres de látex. Ideales para manejo de alimentos y procedimientos de bajo riesgo.',
    unit: 'Caja 100 pzas',
    price: 98,
    category: 'guantes',
    image: '/images/Guante-de-polietileno.jpg',
    keywords: ['guante polietileno', 'guante plástico', 'libre de látex'],
  },
  {
    id: 16,
    slug: 'cubrebocas-economico',
    name: 'Cubrebocas económico',
    description: 'Cubrebocas de tela no tejida de 3 capas con ajuste nasal. Filtración básica, cómodo y ligero para uso diario.',
    unit: 'Caja 50 pzas',
    price: 112,
    category: 'cubrebocas',
    image: '/images/Cubrebocas-económico-azul.jpg',
    keywords: ['cubrebocas', 'mascarilla', 'protección respiratoria', 'tricapa'],
  },
  {
    id: 17,
    slug: 'cubrebocas-pliegues',
    name: 'Cubrebocas con pliegues y ajuste nasal',
    description: 'Cubrebocas con pliegues de expansión y clip metálico nasal. Mayor cobertura y ajuste que el modelo estándar.',
    unit: 'Caja 50 pzas',
    price: 142,
    category: 'cubrebocas',
    image: '/images/Cubreboca-con-pliegues-y-ajuste-nasal.jpg',
    keywords: ['cubrebocas pliegues', 'mascarilla nasal', 'protección facial'],
  },
  {
    id: 18,
    slug: 'bata-cirujano',
    name: 'Bata para cirujano',
    description: 'Bata desechable para cirujano de tela SMS (Spunbond-Meltblown-Spunbond). Impermeable, resistente y con puños elásticos.',
    unit: 'Pieza',
    price: 82,
    category: 'ropa',
    image: '/images/Bata-de-cirujano.jpg',
    keywords: ['bata cirujano', 'ropa quirúrgica', 'desechable', 'SMS'],
  },
  {
    id: 19,
    slug: 'bata-paciente',
    name: 'Bata para paciente',
    description: 'Bata desechable para paciente. Tela suave y transpirable. Con amarres en la espalda, talla única con ajuste.',
    unit: 'Pieza',
    price: 33,
    category: 'ropa',
    image: '/images/Bata-de-cirujano.jpg',
    keywords: ['bata paciente', 'bata hospital', 'desechable'],
  },
  {
    id: 20,
    slug: 'filipina-desechable',
    name: 'Filipina desechable',
    description: 'Filipina (casaca médica) desechable de tela no tejida. Ligera y cómoda, ideal para personal de salud.',
    unit: 'Pieza',
    price: 52,
    category: 'ropa',
    image: '/images/Filipina.jpg',
    keywords: ['filipina', 'casaca médica', 'ropa médica desechable'],
  },
  {
    id: 21,
    slug: 'gorro-redondo',
    name: 'Gorro redondo desechable',
    description: 'Gorro circular desechable de tela no tejida. Elástico perimetral, cómodo y seguro. Para quirófano y clínica.',
    unit: 'Bolsa 100 pzas',
    price: 72,
    category: 'ropa',
    image: '/images/Gorro-redondo.jpg',
    keywords: ['gorro quirúrgico', 'cofia desechable', 'gorro médico'],
  },
  {
    id: 22,
    slug: 'cubre-zapato',
    name: 'Cubre zapato desechable',
    description: 'Cubre zapatos de polietileno no tejido. Antideslizante, elástico y resistente. Para uso en quirófano, clínicas y áreas limpias.',
    unit: 'Bolsa 100 pzas',
    price: 78,
    category: 'ropa',
    image: '/images/Cubre-zapato.jpg',
    keywords: ['cubrezapato', 'protector calzado', 'quirófano'],
  },
  {
    id: 23,
    slug: 'bolsa-rpbi-roja',
    name: 'Bolsa RPBI roja',
    description: 'Bolsa roja para recolección de Residuos Peligrosos Biológico-Infecciosos (RPBI). Calibre resistente, serigrafía reglamentaria NOM-087.',
    unit: 'Paquete 25 pzas',
    price: 142,
    category: 'residuos',
    image: '/images/Bolsa-para-RPBI.jpg',
    keywords: ['bolsa RPBI', 'residuos biológicos', 'NOM-087', 'bolsa roja'],
  },
  {
    id: 24,
    slug: 'recolector-punzocortantes',
    name: 'Recolector de punzocortantes',
    description: 'Contenedor rígido para recolección de material punzocortante (agujas, bisturís). Tapa de seguridad, polipropileno rígido. Cumple NOM-087.',
    unit: 'Pieza',
    price: 57,
    category: 'residuos',
    image: '/images/Recolector-de-punzocortantes.jpg',
    keywords: ['recolector punzocortantes', 'contenedor agujas', 'sharps container', 'NOM-087'],
  },
  {
    id: 25,
    slug: 'recolector-residuos-liquidos',
    name: 'Recolector de residuos líquidos',
    description: 'Recipiente para recolección de residuos líquidos biológicos. Tapa hermética, polietileno de alta densidad.',
    unit: 'Pieza',
    price: 68,
    category: 'residuos',
    image: '/images/Recolector-de-residuos-líquidos.jpg',
    keywords: ['recolector líquidos', 'residuos líquidos', 'RPBI líquidos'],
  },
  {
    id: 26,
    slug: 'bolsa-orina-nino',
    name: 'Bolsa para recolección de orina niño',
    description: 'Bolsa colectora de orina para niño. Adhesivo hipoalergénico, graduada en ml, con válvula anti-retorno.',
    unit: 'Caja 100 pzas',
    price: 240,
    category: 'laboratorio',
    image: '/images/Orina-niño.jpg',
    keywords: ['bolsa orina pediátrica', 'urocultivo niño', 'colector orina'],
  },
  {
    id: 27,
    slug: 'bolsa-orina-nina',
    name: 'Bolsa para recolección de orina niña',
    description: 'Bolsa colectora de orina para niña. Forma anatómica femenina, adhesivo hipoalergénico y graduada.',
    unit: 'Caja 100 pzas',
    price: 248,
    category: 'laboratorio',
    image: '/images/Orina-niña.jpg',
    keywords: ['bolsa orina niña', 'urocultivo niña', 'colector orina femenino'],
  },
  {
    id: 28,
    slug: 'vaso-copro',
    name: 'Vaso copro graduado',
    description: 'Vaso copro de polipropileno transparente con tapa de rosca hermética. Graduado en ml, con paleta integrada. Para muestras de laboratorio.',
    unit: 'Bolsa 50 pzas',
    price: 117,
    category: 'laboratorio',
    image: '/images/Vaso-copro-graduado.jpg',
    keywords: ['vaso copro', 'coprocultivo', 'muestra materia fecal', 'laboratorio'],
  },
  {
    id: 29,
    slug: 'campo-desechable',
    name: 'Campo quirúrgico desechable',
    description: 'Campo quirúrgico desechable de tela SMS. Impermeable, resistente al paso de microorganismos. Varias medidas disponibles.',
    unit: 'Pieza',
    price: 42,
    category: 'ropa',
    image: '/images/Campo-quirúrgico.jpg',
    keywords: ['campo quirúrgico', 'campo estéril', 'campo desechable', 'SMS'],
  },
  {
    id: 30,
    slug: 'gel-refrigerante',
    name: 'Gel refrigerante',
    description: 'Gel frío reutilizable para terapia de frío. Flexible incluso congelado, no tóxico y sin BPA. Ideal para clínicas y rehabilitación.',
    unit: 'Pieza',
    price: 63,
    category: 'laboratorio',
    image: '/images/Gel-Refrigerante.jpg',
    keywords: ['gel frío', 'bolsa frío', 'terapia fría', 'compresa fría'],
  },
]


